### ISSUE TITLE
BIOS DVMT & CFG-Lock

### ISSUE THREAD

**Issue by gatorback** [Bhavinjain260/Asus-Vivobook15-X515JA-Opencore#1]
Does the BIOS allow the user to change DVMT (video memory)?   CFG-Lock?

If you found the DVMT and CFG-Lock hexadecimal offsets: please publish in readme.md?  Thanks

**Comment by Bhavinjain260** [comment]
You will have to use ModGrubshell.efi method will not work 
you will have to use Ru.efi

**Comment by Bhavinjain260** [comment]
https://www.reddit.com/r/hackintosh/comments/hz2rtm/cfg_lockunlocking_alternative_method/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

You can follow this guide

**Comment by Bhavinjain260** [comment]
https://www.reddit.com/r/hackintosh/comments/yc82fw/voltageshift_undervolting_hp_pavillion_x360_10th/
