### ISSUE TITLE
Can't wake screen after it got sleep but everything else seems to be fine and awake (usb, keyboard, even sound)

### ISSUE THREAD

**Issue by ericko7** [Bhavinjain260/Asus-Vivobook15-X515JA-Opencore#2]
Hi! It seems I have the same machine than yours. But I can't solve a problem, when I leave alone my installation process, the laptop get asleep and then I can't make the screen wake (everything else appears to wake fine, the USB, the keyboard, the touchpad, the sound). Did you experienced something like this? I followed Dortania's guide, and also used your post to check/compare/complete my files. Please, any suggestions? any advice? Thanks in advance!

**Comment by Bhavinjain260** [comment]
Share me your config.plist

**Comment by ericko7** [comment]
Thanks for the soon answer. Here it is!
[config.plist.txt](https://github.com/Bhavinjain260/Asus-Vivobook15-X515JA-Opencore/files/11546738/config.plist.txt)

**Comment by Bhavinjain260** [comment]
Are you keeping your laptop pugged in while installing the OS?

**Comment by ericko7** [comment]
Yes, it's  plugged.

**Comment by Bhavinjain260** [comment]
> Yes, it's  plugged. 

What I do is I never let my screen go black.

**Comment by Bhavinjain260** [comment]
Which version of MacOS you are trying to install?
