### ISSUE TITLE
Asus

### ISSUE THREAD

**Issue by FelixxxPSS** [Bhavinjain260/Asus-Vivobook15-X515JA-Opencore#4]
Hello, do you think this model works for me? I will upgrade the ram and maybe change the SSD
https://www.lapolar.cl/notebook-asus-x515ja-core-i3-4gb-256gb-ssd-156/26758025.html?gclid=CjwKCAjw6p-oBhAYEiwAgg2Pgqzf-fMwpFZSYmIclQOPwfq2yeJFcFHuWOBwk_rrDkBlPxIeu4dcuRoCuPYQAvD_BwE

**Comment by Bhavinjain260** [comment]
Not able to open the site on my end 

Share me your lap's specs
